# Welcome to ikuler!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'ikuler serve'. If you change this file, please restart the server process.

# Site settings
title: 略知一二
description: > # this means to ignore newlines until "baseurl:"
  Le vent se lève ，il faut tenter de vivre。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ikuler.github.io" # the base hostname & protocol for your site
# twitter_username: 
github_username:  ikuler

# Build settings
markdown: kramdown

# Google services
#google_analytics: UA-82495353-1

gems:
  - ikuler-seo-tag

#twitter:

logo: /images/nclogo.png

#author:


future: true
