# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 略知一二
email: ikuler@163.com
description: >- # this means to ignore newlines until "baseurl:"
   Le vent se lève ，il faut tenter de vivre。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  ikuler

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

logo: /images/tspsg.png

gems:
  - jekyll-seo-tag

future: true

